<a href="https://colab.research.google.com/github/kunalavghade/Digital_Signal_Processing/blob/main/DCT_and_IDCT/DCT_and_IDCT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Exp3 : DCT and IDCT**

**Name : Kunal Pravin Avghade**

**Roll No : 313057**

**Gr No : 22020031**

**Batch : C3**

In [ ]:
import numpy as np

In [ ]:
x = np.array(list(map(int,input().split())))  
N = len(x)

1 2 4 7


## Calculate DCT

In [ ]:
mat = np.zeros((N, N))

for i in range(N):
  for j in range(N):
      if i == 0:
        mat[i][j] = np.sqrt(1/N)
      else:
        mat[i][j] = np.sqrt(2/N)*np.cos((np.pi*((j*2)+1)*i)/(2*N))
print(mat)

[[ 0.5         0.5         0.5         0.5       ]
 [ 0.65328148  0.27059805 -0.27059805 -0.65328148]
 [ 0.5        -0.5        -0.5         0.5       ]
 [ 0.27059805 -0.65328148  0.65328148 -0.27059805]]


In [ ]:
F = np.dot(mat,x)
F

array([ 7.        , -4.46088499,  1.        , -0.31702534])

## Calculate IDCT

In [ ]:
IDCT = []
for i in range(N):
  sum = 0
  for j in range(N):
    if i == 0:
      sum += np.sqrt(1/N)
    else:
      sum += (np.sqrt(2/N)*F[j]*np.cos((np.pi*((i*2)+1)*j)/(2*N)))
  IDCT.append(sum)

IDCT

[2.0, 3.4497474683058336, 5.449747468305833, 8.449747468305834]